services:
  deploy_engine_test_postgres:
    image: postgres:17.3
    container_name: deploy_engine_test_postgres
    networks:
      - celerity_deploy_engine_test_network
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_PASSWORD}
      POSTGRES_USER: ${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_USER}
    ports:
      - 45433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_DATABASE} -U ${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_USER}"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  deploy_engine_test_postgres_migrate:
    image: migrate/migrate:v4.18.2
    container_name: deploy_engine_test_postgres_migrate
    networks:
      - celerity_deploy_engine_test_network
    command:
      [
        "-source",
        "file:///migrations",
        "-database",
        "pgx5://${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_USER}:${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_PASSWORD}@deploy_engine_test_postgres:5432/${CELERITY_DEPLOY_ENGINE_STATE_POSTGRES_DATABASE}?sslmode=disable",
        "up",
      ]
    links:
      - deploy_engine_test_postgres
    depends_on:
      deploy_engine_test_postgres:
        condition: service_healthy
    volumes:
      - ./postgres/migrations:/migrations

networks:
  celerity_deploy_engine_test_network:
    name: celerity_deploy_engine_test_network
