version: 2

project_name: blueprint-ls
dist: dist

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  # Native builds for each OS/arch combination
  # CGO is required for tree-sitter parsing support
  - id: blueprint-ls-linux-amd64
    main: ./cmd/main.go
    binary: blueprint-ls
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: blueprint-ls-linux-arm64
    main: ./cmd/main.go
    binary: blueprint-ls
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: blueprint-ls-darwin-amd64
    main: ./cmd/main.go
    binary: blueprint-ls
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: blueprint-ls-darwin-arm64
    main: ./cmd/main.go
    binary: blueprint-ls
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: blueprint-ls-windows-amd64
    main: ./cmd/main.go
    binary: blueprint-ls
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: blueprint-ls-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

sboms:
  - id: blueprint-ls-sbom
    artifacts: archive

changelog:
  disable: true

release:
  disable: true
