// Provides functionality for a declared link graph, which is a view of declared
// links within a blueprint that can be used to analyse links and their
// relationships without needing to resolve them.
// This is especially important in enabling rich validation of links between
// abstract resource types defined in transformer plugins.
package links

import (
	"context"
	"slices"

	"github.com/newstack-cloud/bluelink/libs/blueprint/resourcehelpers"
	"github.com/newstack-cloud/bluelink/libs/blueprint/schema"
	"github.com/newstack-cloud/bluelink/libs/blueprint/speccore"
)

// ResourceClass represents the classification of a resource in the context of a declared link graph.
type ResourceClass string

const (
	// ResourceClassConcrete represents a resource that is a concrete resource implemented
	// by a provider plugin.
	ResourceClassConcrete ResourceClass = "concrete"
	// ResourceClassAbstract represents a resource that is an abstract resource defined
	// in a transformer plugin.
	ResourceClassAbstract ResourceClass = "abstract"
)

// DeclaredLinkGraph represents a graph of declared links within a blueprint,
// allowing for analysis of link relationships
// without needing to resolve them.
type DeclaredLinkGraph interface {
	// Edges returns all the edges in the declared link graph.
	Edges() []*ResolvedLink
	// EdgesFrom returns the edges in the graph that have the given resource as the source.
	EdgesFrom(resourceName string) []*ResolvedLink
	// EdgesTo returns the edges in the graph that have the given resource as the target.
	EdgesTo(resourceName string) []*ResolvedLink
	// Resource looks up a resource by name in the graph and returns the resource schema,
	// its classification as concrete or abstract, and whether it was found.
	Resource(name string) (*schema.Resource, ResourceClass, bool)
}

// ResolvedLink represents a link between two resources in the declared link graph.
type ResolvedLink struct {
	// The source resource name.
	Source string
	// The target resource name.
	Target string
	// The source resource type.
	SourceType string
	// The target resource type.
	TargetType string
	// The label keys that matched.
	// In the form "label::<key>:<value>" as per the
	// selector keys generated by GroupResourcesBySelector.
	SelectorKeys []string
}

type resourceEntry struct {
	schema         *schema.Resource
	classification ResourceClass
}

type defaultDeclaredLinkGraph struct {
	edges     []*ResolvedLink
	outgoing  map[string][]*ResolvedLink
	incoming  map[string][]*ResolvedLink
	resources map[string]resourceEntry
}

func (g *defaultDeclaredLinkGraph) Edges() []*ResolvedLink {
	return g.edges
}

func (g *defaultDeclaredLinkGraph) EdgesFrom(resourceName string) []*ResolvedLink {
	if edges, ok := g.outgoing[resourceName]; ok {
		return edges
	}

	return []*ResolvedLink{}
}

func (g *defaultDeclaredLinkGraph) EdgesTo(resourceName string) []*ResolvedLink {
	if edges, ok := g.incoming[resourceName]; ok {
		return edges
	}

	return []*ResolvedLink{}
}

func (g *defaultDeclaredLinkGraph) Resource(name string) (*schema.Resource, ResourceClass, bool) {
	if entry, ok := g.resources[name]; ok {
		return entry.schema, entry.classification, true
	}
	return nil, "", false
}

// EnumerateDeclaredLinks takes a blueprint and resource registry and produces a DeclaredLinkGraph
// representing the declared links within the blueprint.
// This is intended to be used for analysis and validation of links that is inclusive of abstract resources
// defined in transformers without needing to resolve concrete link implementations.
func EnumerateDeclaredLinks(
	ctx context.Context,
	spec *schema.Blueprint,
	resourceRegistry resourcehelpers.Registry,
) (DeclaredLinkGraph, error) {
	groupedResources := GroupResourcesBySelector(
		speccore.BlueprintSpecFromSchema(spec),
	)

	graph := &defaultDeclaredLinkGraph{
		edges:     []*ResolvedLink{},
		outgoing:  make(map[string][]*ResolvedLink),
		incoming:  make(map[string][]*ResolvedLink),
		resources: make(map[string]resourceEntry),
	}

	// Track source -> target -> *ResolvedLink to avoid creating duplicate edges in cases where
	// multiple selector keys match between the same source and target resources.
	pairIndex := map[string]map[string]*ResolvedLink{}

	for selectorKey, selectGroup := range groupedResources {
		err := collectDeclaredLinks(
			ctx, selectGroup, selectorKey, graph, pairIndex, resourceRegistry,
		)
		if err != nil {
			return nil, err
		}
	}

	return graph, nil
}

func collectDeclaredLinks(
	ctx context.Context,
	selectGroup *SelectGroup,
	selectorKey string,
	graph *defaultDeclaredLinkGraph,
	pairIndex map[string]map[string]*ResolvedLink,
	resourceRegistry resourcehelpers.Registry,
) error {
	for _, sourceResourceInfo := range selectGroup.SelectorResources {
		if err := addResourceToGraph(
			ctx, sourceResourceInfo, graph, resourceRegistry,
		); err != nil {
			return err
		}

		for _, targetResourceInfo := range selectGroup.CandidateResourcesForSelection {
			if sourceResourceInfo.Name == targetResourceInfo.Name {
				// Skip self-referencing links where the source and target are the same resource.
				// These can occur when a resource has labels that match its own link selector,
				// but should not be treated as valid links in the graph.
				// This matches the behaviour for concrete link chain resolution in SpecLinkInfo.
				continue
			}

			if err := addResourceToGraph(
				ctx, targetResourceInfo, graph, resourceRegistry,
			); err != nil {
				return err
			}

			targets, ok := pairIndex[sourceResourceInfo.Name]
			if !ok {
				targets = map[string]*ResolvedLink{}
				pairIndex[sourceResourceInfo.Name] = targets
			}

			if existing, seen := targets[targetResourceInfo.Name]; seen {
				if !slices.Contains(existing.SelectorKeys, selectorKey) {
					existing.SelectorKeys = append(existing.SelectorKeys, selectorKey)
				}
				continue
			}

			edge := addEdgeToGraph(graph, sourceResourceInfo, targetResourceInfo, selectorKey)
			targets[targetResourceInfo.Name] = edge
		}
	}

	return nil
}

func addResourceToGraph(
	ctx context.Context,
	resourceInfo *ResourceWithNameAndSelectors,
	graph *defaultDeclaredLinkGraph,
	resourceRegistry resourcehelpers.Registry,
) error {
	if _, exists := graph.resources[resourceInfo.Name]; !exists {
		sourceResourceType := schema.GetResourceType(resourceInfo.Resource)
		sourceClassification := ResourceClassConcrete
		isAbstract, err := resourceRegistry.IsAbstractResourceType(
			ctx,
			sourceResourceType,
		)
		if err != nil {
			return err
		}

		if isAbstract {
			sourceClassification = ResourceClassAbstract
		}

		graph.resources[resourceInfo.Name] = resourceEntry{
			schema:         resourceInfo.Resource,
			classification: sourceClassification,
		}
	}

	return nil
}

func addEdgeToGraph(
	graph *defaultDeclaredLinkGraph,
	sourceResourceInfo *ResourceWithNameAndSelectors,
	targetResourceInfo *ResourceWithNameAndSelectors,
	selectorKey string,
) *ResolvedLink {
	edge := &ResolvedLink{
		Source:       sourceResourceInfo.Name,
		Target:       targetResourceInfo.Name,
		SourceType:   schema.GetResourceType(sourceResourceInfo.Resource),
		TargetType:   schema.GetResourceType(targetResourceInfo.Resource),
		SelectorKeys: []string{selectorKey},
	}
	graph.edges = append(graph.edges, edge)
	graph.outgoing[sourceResourceInfo.Name] = append(
		graph.outgoing[sourceResourceInfo.Name],
		edge,
	)
	graph.incoming[targetResourceInfo.Name] = append(
		graph.incoming[targetResourceInfo.Name],
		edge,
	)
	return edge
}
