version: 2

project_name: bluelink
dist: dist

builds:
  - id: bluelink-cli
    main: ./cmd/main.go
    binary: bluelink
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/newstack-cloud/bluelink/apps/cli/cmd/utils.Version={{ .Version }}
      - -X github.com/newstack-cloud/bluelink/apps/cli/cmd/utils.BuildTime={{ .Date }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: bluelink-cli-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

sboms:
  - id: bluelink-cli-sbom
    artifacts: archive

changelog:
  disable: true

release:
  disable: true
