version: 2

project_name: bluelink-manager
dist: dist

before:
  hooks:
    - go mod download

builds:
  - id: bluelink-manager
    main: ./cmd
    binary: bluelink-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/newstack-cloud/bluelink/tools/bluelink-manager/cmd/commands.Version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: bluelink-manager-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

sboms:
  - id: bluelink-manager-sbom
    artifacts: archive

changelog:
  disable: true

release:
  disable: true
